### ISSUE TITLE
Doesn't work in Iterm2

### ISSUE THREAD

**Issue by slonoed** [atelierbram/vim-colors_duotones#1]
Hello! Thank you for your work.

This colors perfectly work in MacVim, but doesn't work in Iterm.
I tried different Iterm settings, but didn't succeed.
Maybe I missed smth?

**Comment by atelierbram** [comment]
These colorschemes are optimized for the **GUI** version of Vim, like MacVim **not** for the _terminal_ Vi-Vim. In time I will be editing the base16-builder template for iTerm2, so when one would have _the same_ colorscheme there, this would give a more seamless experience. Haven't even tested the recent output file yet, but one can already download it [from here](https://github.com/atelierbram/syntax-highlighting/tree/master/duotones/output/iterm2) but it is **not** finished yet. 
One Vim colorscheme I know of which works fine for both GUI and terminal is [Gruvbox](https://github.com/morhetz/gruvbox). Have been thinking about hacking that one, but somehow it doesn't feel right.

**Comment by slonoed** [comment]
Thank you! This iterm2 themes work!

**Comment by atelierbram** [comment]
Glad it works, but when I can find _the time_ I am going to change some colors around, to be consistent with the spirit of the original DuoTone colorscheme. Will be _the same_ colors though, so well ..., this will have to do for now. Thanks for testing this.
