### ISSUE TITLE
Not working in terminal vim

### ISSUE THREAD

**Issue by shannonmoeller** [atelierbram/vim-colors_duotones#5]
Are these themes intended to work in terminal vim?

**Comment by atelierbram** [comment]
These colorschemes are optimized for the **GUI** version of Vim, like GVim or MacVim **not** for the _terminal_ Vi-Vim. In time I will be editing the base16-builder template for iTerm2, so when one would have _the same_ colorscheme there, this would give a more seamless experience. Haven't even tested the recent output file yet, but one can already download it [from here](https://github.com/atelierbram/syntax-highlighting/tree/master/duotones/output/iterm2) but it is **not** finished yet. 
One Vim colorscheme I know of which works fine for both GUI and terminal is [Gruvbox](https://github.com/morhetz/gruvbox). Have been thinking about hacking that one, but somehow it doesn't feel right.

**Comment by shannonmoeller** [comment]
Thanks for the quick and complete response! I'll checkout those iTerm color profiles and let you know if I have any issues.

**Comment by shannonmoeller** [comment]
Works great so far. Only draw back is that "red" is often blue or green so when I run unit tests, the output looks wrong. Would be nice to invert the use of orange and blue in darkspace for example.

**Comment by atelierbram** [comment]
Thanks, that is something to consider when working on the new version for iTerm2. Will be starting all over with [a rejuvenated templating engine](https://github.com/atelierbram/Base2Tone) (which brings more flexibility) in about a month.
